# Windows/WSL2 specific overrides
# Extends compose.yaml with Windows-specific configurations
# Services are defined in profile files (profiles/*.yaml)

version: '3.8'

# This file can be used to add Windows-specific overrides when needed
# GPU support via WSL2
# Note: GPU services should use device_requests in their profile files

