# Linux x86_64 NVIDIA GPU specific overrides
# Extends compose.yaml with GPU support for Linux amd64
# Services are defined in profile files (profiles/*.yaml)

version: '3.8'

# This file can be used to add Linux amd64-specific overrides when needed
# GPU services will use device_requests in their profile files

