# Repository management script for crossplay (PowerShell)
# Allows adding, removing, listing, and updating sibling repositories

$ErrorActionPreference = "Stop"

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$ProjectRoot = Split-Path -Parent $ScriptDir

$ConfigFile = Join-Path $ProjectRoot "config\crossplay.config.yaml"
$EnvFile = Join-Path $ProjectRoot ".env"

# Ensure config directory exists
$ConfigDir = Join-Path $ProjectRoot "config"
if (-not (Test-Path $ConfigDir)) {
    New-Item -ItemType Directory -Path $ConfigDir | Out-Null
}

function Show-Usage {
    Write-Host "Usage: .\manage-repos.ps1 {add|remove|list|update} [type] [path]"
    Write-Host ""
    Write-Host "Commands:"
    Write-Host "  add <type> <path>    - Add/connect a repository"
    Write-Host "  remove <type>        - Remove a repository"
    Write-Host "  list                 - List all repositories"
    Write-Host "  update <type> <path> - Update repository path"
    Write-Host ""
    Write-Host "Types: video, ros2, nlp, or custom"
    exit 1
}

function Backup-Config {
    if (Test-Path $ConfigFile) {
        Copy-Item $ConfigFile "$ConfigFile.bak"
    }
    if (Test-Path $EnvFile) {
        Copy-Item $EnvFile "$EnvFile.bak"
    }
}

function Restore-Config {
    if (Test-Path "$ConfigFile.bak") {
        Move-Item -Force "$ConfigFile.bak" $ConfigFile
    }
    if (Test-Path "$EnvFile.bak") {
        Move-Item -Force "$EnvFile.bak" $EnvFile
    }
}

function Test-ContainerRunning {
    param([string]$Service)
    $containerName = "crossplay_$Service"
    $containers = docker ps --format '{{.Names}}' 2>$null
    return $containers -match "^$containerName$"
}

function Add-Repo {
    param([string]$Type, [string]$Path)
    
    if ([string]::IsNullOrWhiteSpace($Type) -or [string]::IsNullOrWhiteSpace($Path)) {
        Write-Host "ERROR: Type and path are required" -ForegroundColor Red
        Show-Usage
    }
    
    # Validate path
    try {
        $AbsPath = Resolve-Path (Join-Path $ProjectRoot $Path) -ErrorAction Stop
        if (-not (Test-Path $AbsPath -PathType Container)) {
            throw "Path is not a directory"
        }
    } catch {
        Write-Host "ERROR: Repository path does not exist: $Path" -ForegroundColor Red
        exit 1
    }
    
    Write-Host "Adding repository: $Type -> $AbsPath"
    
    # Backup config
    Backup-Config
    
    # Create config if it doesn't exist
    if (-not (Test-Path $ConfigFile)) {
        @"
# Crossplay Configuration
# Generated by manage-repos script

repositories:
"@ | Out-File -FilePath $ConfigFile -Encoding UTF8
    }
    
    # Check if repo already exists
    $ConfigContent = Get-Content $ConfigFile -Raw
    if ($ConfigContent -match "^\s+${Type}:") {
        Write-Host "WARNING: Repository $Type already exists. Use 'update' command to change path." -ForegroundColor Yellow
        Restore-Config
        exit 1
    }
    
    # Add to config
    Add-Content -Path $ConfigFile -Value @"

  ${Type}:
    enabled: true
    path: $($AbsPath.Path)
    type: ${Type}
"@
    
    # Update .env file
    if (Test-Path $EnvFile) {
        $EnvVar = "$Type".ToUpper() + "_PATH"
        $EnvContent = Get-Content $EnvFile
        $Updated = $false
        $NewContent = $EnvContent | ForEach-Object {
            if ($_ -match "^${EnvVar}=") {
                $Updated = $true
                "${EnvVar}=$($AbsPath.Path)"
            } else {
                $_
            }
        }
        if (-not $Updated) {
            $NewContent += "${EnvVar}=$($AbsPath.Path)"
        }
        $NewContent | Set-Content $EnvFile
    }
    
    # Stop container if running
    if (Test-ContainerRunning $Type) {
        Write-Host "Stopping existing container for $Type..."
        docker stop "crossplay_${Type}" 2>$null
    }
    
    Write-Host "✓ Repository $Type added successfully" -ForegroundColor Green
    Write-Host "  Path: $($AbsPath.Path)"
    Write-Host ""
    Write-Host "Run .\scripts\launch.ps1 to start services with the new repository"
}

function Remove-Repo {
    param([string]$Type)
    
    if ([string]::IsNullOrWhiteSpace($Type)) {
        Write-Host "ERROR: Type is required" -ForegroundColor Red
        Show-Usage
    }
    
    if (-not (Test-Path $ConfigFile)) {
        Write-Host "ERROR: Configuration file not found" -ForegroundColor Red
        exit 1
    }
    
    $ConfigContent = Get-Content $ConfigFile -Raw
    if ($ConfigContent -notmatch "^\s+${Type}:") {
        Write-Host "ERROR: Repository $Type not found" -ForegroundColor Red
        exit 1
    }
    
    Write-Host "Removing repository: $Type"
    
    # Stop container if running
    if (Test-ContainerRunning $Type) {
        Write-Host "Stopping container for $Type..."
        docker stop "crossplay_${Type}" 2>$null
        docker rm "crossplay_${Type}" 2>$null
    }
    
    # Backup config
    Backup-Config
    
    # Remove from config (simple regex approach)
    $Lines = Get-Content $ConfigFile
    $NewLines = @()
    $InSection = $false
    foreach ($line in $Lines) {
        if ($line -match "^\s+${Type}:") {
            $InSection = $true
            continue
        }
        if ($InSection -and $line -match "^\s+[a-z]+:") {
            $InSection = $false
        }
        if (-not $InSection) {
            $NewLines += $line
        }
    }
    $NewLines | Set-Content $ConfigFile
    
    # Update .env file
    if (Test-Path $EnvFile) {
        $EnvVar = "$Type".ToUpper() + "_PATH"
        $EnvContent = Get-Content $EnvFile | Where-Object { $_ -notmatch "^${EnvVar}=" }
        $EnvContent | Set-Content $EnvFile
    }
    
    Write-Host "✓ Repository $Type removed successfully" -ForegroundColor Green
}

function List-Repos {
    if (-not (Test-Path $ConfigFile)) {
        Write-Host "No repositories configured"
        Write-Host "Run '.\scripts\setup.ps1' or '.\scripts\manage-repos.ps1 add <type> <path>' to add repositories"
        exit 0
    }
    
    Write-Host "=== Configured Repositories ===" -ForegroundColor Cyan
    Write-Host ""
    
    $ConfigContent = Get-Content $ConfigFile -Raw
    $Repos = [regex]::Matches($ConfigContent, "(?s)(\s+)([a-z]+):\s*\n\s+enabled:\s*(true|false)\s*\n\s+path:\s*(.+?)\s*\n\s+type:")
    
    foreach ($Match in $Repos) {
        $Type = $Match.Groups[2].Value
        $Enabled = $Match.Groups[3].Value
        $Path = $Match.Groups[4].Value
        
        $Status = "stopped"
        if (Test-ContainerRunning $Type) {
            $Status = "running"
        }
        
        Write-Host "Type: $Type"
        Write-Host "  Enabled: $Enabled"
        Write-Host "  Path: $Path"
        Write-Host "  Container: $Status"
        Write-Host ""
    }
}

function Update-Repo {
    param([string]$Type, [string]$Path)
    
    if ([string]::IsNullOrWhiteSpace($Type) -or [string]::IsNullOrWhiteSpace($Path)) {
        Write-Host "ERROR: Type and path are required" -ForegroundColor Red
        Show-Usage
    }
    
    if (-not (Test-Path $ConfigFile)) {
        Write-Host "ERROR: Configuration file not found" -ForegroundColor Red
        exit 1
    }
    
    $ConfigContent = Get-Content $ConfigFile -Raw
    if ($ConfigContent -notmatch "^\s+${Type}:") {
        Write-Host "ERROR: Repository $Type not found. Use 'add' command to add it." -ForegroundColor Red
        exit 1
    }
    
    # Validate path
    try {
        $AbsPath = Resolve-Path (Join-Path $ProjectRoot $Path) -ErrorAction Stop
        if (-not (Test-Path $AbsPath -PathType Container)) {
            throw "Path is not a directory"
        }
    } catch {
        Write-Host "ERROR: Repository path does not exist: $Path" -ForegroundColor Red
        exit 1
    }
    
    Write-Host "Updating repository: $Type -> $AbsPath"
    
    # Backup config
    Backup-Config
    
    # Update path in config
    $ConfigContent = $ConfigContent -replace "(?s)(\s+${Type}:.*?path:\s*)(.+?)(\s+type:)", "`$1$($AbsPath.Path)`$3"
    $ConfigContent | Set-Content $ConfigFile
    
    # Update .env file
    if (Test-Path $EnvFile) {
        $EnvVar = "$Type".ToUpper() + "_PATH"
        $EnvContent = Get-Content $EnvFile | ForEach-Object {
            if ($_ -match "^${EnvVar}=") {
                "${EnvVar}=$($AbsPath.Path)"
            } else {
                $_
            }
        }
        $EnvContent | Set-Content $EnvFile
    }
    
    # Restart container if running
    if (Test-ContainerRunning $Type) {
        Write-Host "Restarting container for $Type..."
        docker restart "crossplay_${Type}" 2>$null
    }
    
    Write-Host "✓ Repository $Type updated successfully" -ForegroundColor Green
    Write-Host "  New path: $($AbsPath.Path)"
}

# Main command handling
$Command = $args[0]
switch ($Command) {
    "add" {
        Add-Repo $args[1] $args[2]
    }
    "remove" {
        Remove-Repo $args[1]
    }
    "list" {
        List-Repos
    }
    "update" {
        Update-Repo $args[1] $args[2]
    }
    default {
        Show-Usage
    }
}

