# Crossplay setup script for Windows PowerShell
# Detects host platform and sets up configuration

$ErrorActionPreference = "Stop"

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$ProjectRoot = Split-Path -Parent $ScriptDir

# Source host detection
. "$ProjectRoot\tools\detect_host.ps1"

Write-Host "=== Crossplay Setup ===" -ForegroundColor Cyan
Write-Host ""
Write-Host "Host Detection Results:"
Write-Host "  OS: $OS"
Write-Host "  Architecture: $ARCH"
Write-Host "  Has GPU: $HAS_GPU"
Write-Host "  Is Jetson: $IS_JETSON"
Write-Host "  Is Raspberry Pi: $IS_RASPBERRY_PI"
Write-Host "  Profile: $CROSSPLAY_PROFILE"
Write-Host ""

# Check Docker availability
try {
    $dockerVersion = docker --version
    Write-Host "Docker is available: $dockerVersion" -ForegroundColor Green
} catch {
    Write-Host "ERROR: Docker is not installed or not in PATH" -ForegroundColor Red
    Write-Host "Please install Docker Desktop and try again"
    exit 1
}

try {
    docker info | Out-Null
    Write-Host "Docker daemon is running" -ForegroundColor Green
} catch {
    Write-Host "ERROR: Docker daemon is not running" -ForegroundColor Red
    Write-Host "Please start Docker Desktop and try again"
    exit 1
}

Write-Host ""

# Create config directory if it doesn't exist
$ConfigDir = Join-Path $ProjectRoot "config"
if (-not (Test-Path $ConfigDir)) {
    New-Item -ItemType Directory -Path $ConfigDir | Out-Null
}

# Initialize repositories config
$ReposConfig = Join-Path $ConfigDir "crossplay.config.yaml"
$ConfigContent = @"
# Crossplay Configuration
# Generated by setup script

host:
  os: $OS
  arch: $ARCH
  has_gpu: $HAS_GPU
  is_jetson: $IS_JETSON
  is_raspberry_pi: $IS_RASPBERRY_PI
  profile: $CROSSPLAY_PROFILE

repositories:
"@

# Interactive repo selection
Write-Host "=== Repository Configuration ===" -ForegroundColor Cyan
Write-Host "Please specify paths to sibling repositories (press Enter to skip)"
Write-Host ""

# Video processing repo
$VideoPath = Read-Host "Video processing repo path [../video-processing]"
if ([string]::IsNullOrWhiteSpace($VideoPath)) {
    $VideoPath = "../video-processing"
}
$VideoAbs = Resolve-Path (Join-Path $ProjectRoot $VideoPath) -ErrorAction SilentlyContinue
if ($VideoAbs -and (Test-Path $VideoAbs -PathType Container)) {
    Write-Host "  ✓ Video repo found: $VideoAbs" -ForegroundColor Green
    $ConfigContent += @"

  video:
    enabled: true
    path: $($VideoAbs.Path)
    type: video
"@
} else {
    Write-Host "  ✗ Video repo not found at $VideoPath (will be disabled)" -ForegroundColor Yellow
    $ConfigContent += @"

  video:
    enabled: false
    path: null
    type: video
"@
}

# ROS2 repo
$Ros2Path = Read-Host "ROS2/robot-control repo path [../robot-control]"
if ([string]::IsNullOrWhiteSpace($Ros2Path)) {
    $Ros2Path = "../robot-control"
}
$Ros2Abs = Resolve-Path (Join-Path $ProjectRoot $Ros2Path) -ErrorAction SilentlyContinue
if ($Ros2Abs -and (Test-Path $Ros2Abs -PathType Container)) {
    Write-Host "  ✓ ROS2 repo found: $Ros2Abs" -ForegroundColor Green
    $ConfigContent += @"

  ros2:
    enabled: true
    path: $($Ros2Abs.Path)
    type: ros2
"@
} else {
    Write-Host "  ✗ ROS2 repo not found at $Ros2Path (will be disabled)" -ForegroundColor Yellow
    $ConfigContent += @"

  ros2:
    enabled: false
    path: null
    type: ros2
"@
}

# NLP repo
$NlpPath = Read-Host "NLP service repo path [../nlp-service]"
if ([string]::IsNullOrWhiteSpace($NlpPath)) {
    $NlpPath = "../nlp-service"
}
$NlpAbs = Resolve-Path (Join-Path $ProjectRoot $NlpPath) -ErrorAction SilentlyContinue
if ($NlpAbs -and (Test-Path $NlpAbs -PathType Container)) {
    Write-Host "  ✓ NLP repo found: $NlpAbs" -ForegroundColor Green
    $ConfigContent += @"

  nlp:
    enabled: true
    path: $($NlpAbs.Path)
    type: nlp
"@
} else {
    Write-Host "  ✗ NLP repo not found at $NlpPath (will be disabled)" -ForegroundColor Yellow
    $ConfigContent += @"

  nlp:
    enabled: false
    path: null
    type: nlp
"@
}

$ConfigContent | Out-File -FilePath $ReposConfig -Encoding UTF8
Write-Host ""
Write-Host "Configuration saved to $ReposConfig" -ForegroundColor Green
Write-Host ""

# Generate .env file from .env.example
$EnvFile = Join-Path $ProjectRoot ".env"
if (-not (Test-Path $EnvFile)) {
    $EnvExample = Join-Path $ProjectRoot ".env.example"
    if (Test-Path $EnvExample) {
        Copy-Item $EnvExample $EnvFile
        
        # Update .env with detected profile and paths
        (Get-Content $EnvFile) | ForEach-Object {
            if ($_ -match "^CROSSPLAY_PROFILE=") {
                "CROSSPLAY_PROFILE=$CROSSPLAY_PROFILE"
            } elseif ($_ -match "^VIDEO_PATH=") {
                "VIDEO_PATH=$($VideoAbs.Path)"
            } elseif ($_ -match "^ROS2_PATH=") {
                "ROS2_PATH=$($Ros2Abs.Path)"
            } elseif ($_ -match "^NLP_PATH=") {
                "NLP_PATH=$($NlpAbs.Path)"
            } else {
                $_
            }
        } | Set-Content $EnvFile
        
        Write-Host ".env file created from .env.example" -ForegroundColor Green
    } else {
        Write-Host "WARNING: .env.example not found, creating basic .env" -ForegroundColor Yellow
        @"
COMPOSE_PROJECT_NAME=crossplay
NETWORK_NAME=crossplay_net
CROSSPLAY_PROFILE=$CROSSPLAY_PROFILE
VIDEO_PATH=$($VideoAbs.Path)
ROS2_PATH=$($Ros2Abs.Path)
NLP_PATH=$($NlpAbs.Path)
VIDEO_PORT=8081
NLP_PORT=8082
ROS_DOMAIN_ID=0
"@ | Out-File -FilePath $EnvFile -Encoding UTF8
    }
} else {
    Write-Host ".env file already exists, skipping creation" -ForegroundColor Yellow
}

Write-Host ""
Write-Host "=== Setup Complete ===" -ForegroundColor Cyan
Write-Host ""
Write-Host "Next steps:"
Write-Host "  1. Review and edit .env if needed"
Write-Host "  2. Review config/crossplay.config.yaml"
Write-Host "  3. Run .\scripts\launch.ps1 to start services"
Write-Host ""

