# Crossplay setup script for Windows PowerShell
# Detects host platform and sets up configuration

$ErrorActionPreference = "Stop"

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$ProjectRoot = Split-Path -Parent $ScriptDir

# Source host detection
. "$ProjectRoot\tools\detect_host.ps1"

Write-Host "=== Crossplay Setup ===" -ForegroundColor Cyan
Write-Host ""
Write-Host "Host Detection Results:"
Write-Host "  OS: $OS"
Write-Host "  Architecture: $ARCH"
Write-Host "  Has GPU: $HAS_GPU"
Write-Host "  Is Jetson: $IS_JETSON"
Write-Host "  Is Raspberry Pi: $IS_RASPBERRY_PI"
Write-Host "  Profile: $CROSSPLAY_PROFILE"
Write-Host ""

# Check Docker availability
try {
    $dockerVersion = docker --version
    Write-Host "Docker is available: $dockerVersion" -ForegroundColor Green
} catch {
    Write-Host "ERROR: Docker is not installed or not in PATH" -ForegroundColor Red
    Write-Host "Please install Docker Desktop and try again"
    exit 1
}

try {
    docker info | Out-Null
    Write-Host "Docker daemon is running" -ForegroundColor Green
} catch {
    Write-Host "ERROR: Docker daemon is not running" -ForegroundColor Red
    Write-Host "Please start Docker Desktop and try again"
    exit 1
}

Write-Host ""

# Create config directory if it doesn't exist
$ConfigDir = Join-Path $ProjectRoot "config"
if (-not (Test-Path $ConfigDir)) {
    New-Item -ItemType Directory -Path $ConfigDir | Out-Null
}

# Initialize repositories config
$ReposConfig = Join-Path $ConfigDir "crossplay.config.yaml"
$ConfigContent = @"
# Crossplay Configuration
# Generated by setup script

host:
  os: $OS
  arch: $ARCH
  has_gpu: $HAS_GPU
  is_jetson: $IS_JETSON
  is_raspberry_pi: $IS_RASPBERRY_PI
  profile: $CROSSPLAY_PROFILE

repositories:
"@

# Interactive repo selection
Write-Host "=== Repository Configuration ===" -ForegroundColor Cyan
Write-Host "Add sibling repositories. Enter repo name and path for each repository."
Write-Host "Common repo types: video, ros2, nlp (or any custom name)"
Write-Host "Type 'done' when finished adding repositories."
Write-Host ""

$RepoCount = 0
$VideoAbs = $null
$Ros2Abs = $null
$NlpAbs = $null

while ($true) {
    $RepoName = Read-Host "Repository name (or 'done' to finish)"
    $RepoName = $RepoName.Trim().ToLower()
    
    if ([string]::IsNullOrWhiteSpace($RepoName)) {
        continue
    }
    
    if ($RepoName -eq "done" -or $RepoName -eq "exit" -or $RepoName -eq "quit") {
        break
    }
    
    # Suggest default paths for common repo types
    $DefaultPath = ""
    switch ($RepoName) {
        "video" { $DefaultPath = "../video-processing" }
        "ros2" { $DefaultPath = "../robot-control" }
        "robot-control" { $DefaultPath = "../robot-control" }
        "nlp" { $DefaultPath = "../nlp-service" }
    }
    
    if ($DefaultPath) {
        $RepoPath = Read-Host "Repository path [$DefaultPath]"
        if ([string]::IsNullOrWhiteSpace($RepoPath)) {
            $RepoPath = $DefaultPath
        }
    } else {
        $RepoPath = Read-Host "Repository path"
    }
    
    if ([string]::IsNullOrWhiteSpace($RepoPath)) {
        Write-Host "  ✗ Path cannot be empty, skipping..." -ForegroundColor Yellow
        continue
    }
    
    # Convert to absolute path
    try {
        $RepoAbs = Resolve-Path (Join-Path $ProjectRoot $RepoPath) -ErrorAction Stop
        if (-not (Test-Path $RepoAbs -PathType Container)) {
            throw "Not a directory"
        }
    } catch {
        Write-Host "  ✗ Repository not found at $RepoPath" -ForegroundColor Yellow
        $AddAnyway = Read-Host "  Add anyway? (y/N)"
        if ($AddAnyway -match "^[Yy]$") {
            $ConfigContent += @"

  ${RepoName}:
    enabled: true
    path: $RepoPath
    type: ${RepoName}
"@
            $RepoCount++
        } else {
            Write-Host "  Skipping $RepoName" -ForegroundColor Yellow
        }
        Write-Host ""
        continue
    }
    
    Write-Host "  ✓ $RepoName repo found: $($RepoAbs.Path)" -ForegroundColor Green
    $ConfigContent += @"

  ${RepoName}:
    enabled: true
    path: $($RepoAbs.Path)
    type: ${RepoName}
"@
    $RepoCount++
    
    # Update .env variables for common types
    switch ($RepoName) {
        "video" { $VideoAbs = $RepoAbs }
        "ros2" { $Ros2Abs = $RepoAbs }
        "robot-control" { $Ros2Abs = $RepoAbs }
        "nlp" { $NlpAbs = $RepoAbs }
    }
    Write-Host ""
}

if ($RepoCount -eq 0) {
    Write-Host "No repositories added. You can add them later with: .\scripts\manage-repos.ps1 add <name> <path>" -ForegroundColor Yellow
}

$ConfigContent | Out-File -FilePath $ReposConfig -Encoding UTF8
Write-Host ""
Write-Host "Configuration saved to $ReposConfig" -ForegroundColor Green
Write-Host ""

# Generate .env file from .env.example
$EnvFile = Join-Path $ProjectRoot ".env"
if (-not (Test-Path $EnvFile)) {
    $EnvExample = Join-Path $ProjectRoot ".env.example"
    if (Test-Path $EnvExample) {
        Copy-Item $EnvExample $EnvFile
        
        # Update .env with detected profile
        (Get-Content $EnvFile) | ForEach-Object {
            if ($_ -match "^CROSSPLAY_PROFILE=") {
                "CROSSPLAY_PROFILE=$CROSSPLAY_PROFILE"
            } elseif ($_ -match "^VIDEO_PATH=" -and $VideoAbs) {
                "VIDEO_PATH=$($VideoAbs.Path)"
            } elseif ($_ -match "^ROS2_PATH=" -and $Ros2Abs) {
                "ROS2_PATH=$($Ros2Abs.Path)"
            } elseif ($_ -match "^NLP_PATH=" -and $NlpAbs) {
                "NLP_PATH=$($NlpAbs.Path)"
            } else {
                $_
            }
        } | Set-Content $EnvFile
        
        Write-Host ".env file created from .env.example" -ForegroundColor Green
    } else {
        Write-Host "WARNING: .env.example not found, creating basic .env" -ForegroundColor Yellow
        $EnvContent = @"
COMPOSE_PROJECT_NAME=crossplay
NETWORK_NAME=crossplay_net
CROSSPLAY_PROFILE=$CROSSPLAY_PROFILE
"@
        # Add repo paths if they were set
        if ($VideoAbs) {
            $EnvContent += "`nVIDEO_PATH=$($VideoAbs.Path)"
        }
        if ($Ros2Abs) {
            $EnvContent += "`nROS2_PATH=$($Ros2Abs.Path)"
        }
        if ($NlpAbs) {
            $EnvContent += "`nNLP_PATH=$($NlpAbs.Path)"
        }
        $EnvContent += @"

VIDEO_PORT=8081
NLP_PORT=8082
ROS_DOMAIN_ID=0
"@
        $EnvContent | Out-File -FilePath $EnvFile -Encoding UTF8
    }
} else {
    Write-Host ".env file already exists, skipping creation" -ForegroundColor Yellow
}

Write-Host ""
Write-Host "=== Setup Complete ===" -ForegroundColor Cyan
Write-Host ""
Write-Host "Next steps:"
Write-Host "  1. Review and edit .env if needed"
Write-Host "  2. Review config/crossplay.config.yaml"
Write-Host "  3. Run .\scripts\launch.ps1 to start services"
Write-Host ""

