#!/bin/bash
# Crossplay setup script for Linux/macOS
# Detects host platform and sets up configuration

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# Source host detection
source "$PROJECT_ROOT/tools/detect_host.sh"

echo "=== Crossplay Setup ==="
echo ""
echo "Host Detection Results:"
echo "  OS: $OS"
echo "  Architecture: $ARCH"
echo "  Has GPU: $HAS_GPU"
echo "  Is Jetson: $IS_JETSON"
echo "  Is Raspberry Pi: $IS_RASPBERRY_PI"
echo "  Profile: $CROSSPLAY_PROFILE"
echo ""

# Check Docker availability
if ! command -v docker &> /dev/null; then
    echo "ERROR: Docker is not installed or not in PATH"
    echo "Please install Docker and try again"
    exit 1
fi

if ! docker info &> /dev/null; then
    echo "ERROR: Docker daemon is not running"
    echo "Please start Docker and try again"
    exit 1
fi

echo "Docker is available and running"
echo ""

# Create config directory if it doesn't exist
mkdir -p "$PROJECT_ROOT/config"

# Initialize repositories config
REPOS_CONFIG="$PROJECT_ROOT/config/crossplay.config.yaml"
cat > "$REPOS_CONFIG" << EOF
# Crossplay Configuration
# Generated by setup script

host:
  os: $OS
  arch: $ARCH
  has_gpu: $HAS_GPU
  is_jetson: $IS_JETSON
  is_raspberry_pi: $IS_RASPBERRY_PI
  profile: $CROSSPLAY_PROFILE

repositories:
EOF

# Interactive repo selection
echo "=== Repository Configuration ==="
echo "Add sibling repositories. Enter repo name and path for each repository."
echo "Common repo types: video, ros2, nlp (or any custom name)"
echo "Type 'done' when finished adding repositories."
echo ""

REPO_COUNT=0
while true; do
    read -p "Repository name (or 'done' to finish): " REPO_NAME
    REPO_NAME=$(echo "$REPO_NAME" | tr '[:upper:]' '[:lower:]' | xargs)
    
    if [ -z "$REPO_NAME" ]; then
        continue
    fi
    
    if [ "$REPO_NAME" = "done" ] || [ "$REPO_NAME" = "exit" ] || [ "$REPO_NAME" = "quit" ]; then
        break
    fi
    
    # Suggest default paths for common repo types
    DEFAULT_PATH=""
    case "$REPO_NAME" in
        video)
            DEFAULT_PATH="../video-processing"
            ;;
        ros2|robot-control)
            DEFAULT_PATH="../robot-control"
            ;;
        nlp)
            DEFAULT_PATH="../nlp-service"
            ;;
    esac
    
    if [ -n "$DEFAULT_PATH" ]; then
        read -p "Repository path [$DEFAULT_PATH]: " REPO_PATH
        REPO_PATH=${REPO_PATH:-$DEFAULT_PATH}
    else
        read -p "Repository path: " REPO_PATH
    fi
    
    if [ -z "$REPO_PATH" ]; then
        echo "  ✗ Path cannot be empty, skipping..."
        continue
    fi
    
    # Convert to absolute path
    REPO_ABS=$(cd "$PROJECT_ROOT" && cd "$REPO_PATH" 2>/dev/null && pwd || echo "")
    
    if [ -n "$REPO_ABS" ] && [ -d "$REPO_ABS" ]; then
        echo "  ✓ $REPO_NAME repo found: $REPO_ABS"
        cat >> "$REPOS_CONFIG" << EOF
  ${REPO_NAME}:
    enabled: true
    path: $REPO_ABS
    type: ${REPO_NAME}
EOF
        REPO_COUNT=$((REPO_COUNT + 1))
        
        # Update .env variables for common types
        case "$REPO_NAME" in
            video)
                VIDEO_ABS="$REPO_ABS"
                ;;
            ros2|robot-control)
                ROS2_ABS="$REPO_ABS"
                ;;
            nlp)
                NLP_ABS="$REPO_ABS"
                ;;
        esac
    else
        echo "  ✗ Repository not found at $REPO_PATH"
        read -p "  Add anyway? (y/N): " ADD_ANYWAY
        if [[ "$ADD_ANYWAY" =~ ^[Yy]$ ]]; then
            cat >> "$REPOS_CONFIG" << EOF
  ${REPO_NAME}:
    enabled: true
    path: $REPO_PATH
    type: ${REPO_NAME}
EOF
            REPO_COUNT=$((REPO_COUNT + 1))
        else
            echo "  Skipping $REPO_NAME"
        fi
    fi
    echo ""
done

if [ $REPO_COUNT -eq 0 ]; then
    echo "No repositories added. You can add them later with: ./scripts/manage-repos.sh add <name> <path>"
fi

echo ""
echo "Configuration saved to $REPOS_CONFIG"
echo ""

# Generate .env file from .env.example
if [ ! -f "$PROJECT_ROOT/.env" ]; then
    if [ -f "$PROJECT_ROOT/.env.example" ]; then
        cp "$PROJECT_ROOT/.env.example" "$PROJECT_ROOT/.env"
        
        # Update .env with detected profile
        sed -i.bak "s|^CROSSPLAY_PROFILE=.*|CROSSPLAY_PROFILE=$CROSSPLAY_PROFILE|" "$PROJECT_ROOT/.env"
        
        # Update .env with repo paths (only if they were set)
        if [ -n "$VIDEO_ABS" ]; then
            sed -i.bak "s|^VIDEO_PATH=.*|VIDEO_PATH=$VIDEO_ABS|" "$PROJECT_ROOT/.env"
        fi
        if [ -n "$ROS2_ABS" ]; then
            sed -i.bak "s|^ROS2_PATH=.*|ROS2_PATH=$ROS2_ABS|" "$PROJECT_ROOT/.env"
        fi
        if [ -n "$NLP_ABS" ]; then
            sed -i.bak "s|^NLP_PATH=.*|NLP_PATH=$NLP_ABS|" "$PROJECT_ROOT/.env"
        fi
        rm -f "$PROJECT_ROOT/.env.bak"
        
        echo ".env file created from .env.example"
    else
        echo "WARNING: .env.example not found, creating basic .env"
        cat > "$PROJECT_ROOT/.env" << EOF
COMPOSE_PROJECT_NAME=crossplay
NETWORK_NAME=crossplay_net
CROSSPLAY_PROFILE=$CROSSPLAY_PROFILE
EOF
        # Add repo paths if they were set
        if [ -n "$VIDEO_ABS" ]; then
            echo "VIDEO_PATH=$VIDEO_ABS" >> "$PROJECT_ROOT/.env"
        fi
        if [ -n "$ROS2_ABS" ]; then
            echo "ROS2_PATH=$ROS2_ABS" >> "$PROJECT_ROOT/.env"
        fi
        if [ -n "$NLP_ABS" ]; then
            echo "NLP_PATH=$NLP_ABS" >> "$PROJECT_ROOT/.env"
        fi
        cat >> "$PROJECT_ROOT/.env" << EOF
VIDEO_PORT=8081
NLP_PORT=8082
ROS_DOMAIN_ID=0
EOF
    fi
else
    echo ".env file already exists, skipping creation"
fi

echo ""
echo "=== Setup Complete ==="
echo ""
echo "Next steps:"
echo "  1. Review and edit .env if needed"
echo "  2. Review config/crossplay.config.yaml"
echo "  3. Run ./scripts/launch.sh to start services"
echo ""

