#!/bin/bash
# Crossplay setup script for Linux/macOS
# Detects host platform and sets up configuration

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# Source host detection
source "$PROJECT_ROOT/tools/detect_host.sh"

echo "=== Crossplay Setup ==="
echo ""
echo "Host Detection Results:"
echo "  OS: $OS"
echo "  Architecture: $ARCH"
echo "  Has GPU: $HAS_GPU"
echo "  Is Jetson: $IS_JETSON"
echo "  Is Raspberry Pi: $IS_RASPBERRY_PI"
echo "  Profile: $CROSSPLAY_PROFILE"
echo ""

# Check Docker availability
if ! command -v docker &> /dev/null; then
    echo "ERROR: Docker is not installed or not in PATH"
    echo "Please install Docker and try again"
    exit 1
fi

if ! docker info &> /dev/null; then
    echo "ERROR: Docker daemon is not running"
    echo "Please start Docker and try again"
    exit 1
fi

echo "Docker is available and running"
echo ""

# Create config directory if it doesn't exist
mkdir -p "$PROJECT_ROOT/config"

# Initialize repositories config
REPOS_CONFIG="$PROJECT_ROOT/config/crossplay.config.yaml"
cat > "$REPOS_CONFIG" << EOF
# Crossplay Configuration
# Generated by setup script

host:
  os: $OS
  arch: $ARCH
  has_gpu: $HAS_GPU
  is_jetson: $IS_JETSON
  is_raspberry_pi: $IS_RASPBERRY_PI
  profile: $CROSSPLAY_PROFILE

repositories:
EOF

# Interactive repo selection
echo "=== Repository Configuration ==="
echo "Please specify paths to sibling repositories (press Enter to skip)"
echo ""

# Video processing repo
read -p "Video processing repo path [../video-processing]: " VIDEO_PATH
VIDEO_PATH=${VIDEO_PATH:-../video-processing}
VIDEO_ABS=$(cd "$PROJECT_ROOT" && cd "$VIDEO_PATH" 2>/dev/null && pwd || echo "")
if [ -n "$VIDEO_ABS" ] && [ -d "$VIDEO_ABS" ]; then
    echo "  ✓ Video repo found: $VIDEO_ABS"
    cat >> "$REPOS_CONFIG" << EOF
  video:
    enabled: true
    path: $VIDEO_ABS
    type: video
EOF
else
    echo "  ✗ Video repo not found at $VIDEO_PATH (will be disabled)"
    cat >> "$REPOS_CONFIG" << EOF
  video:
    enabled: false
    path: null
    type: video
EOF
fi

# ROS2 repo
read -p "ROS2/robot-control repo path [../robot-control]: " ROS2_PATH
ROS2_PATH=${ROS2_PATH:-../robot-control}
ROS2_ABS=$(cd "$PROJECT_ROOT" && cd "$ROS2_PATH" 2>/dev/null && pwd || echo "")
if [ -n "$ROS2_ABS" ] && [ -d "$ROS2_ABS" ]; then
    echo "  ✓ ROS2 repo found: $ROS2_ABS"
    cat >> "$REPOS_CONFIG" << EOF
  ros2:
    enabled: true
    path: $ROS2_ABS
    type: ros2
EOF
else
    echo "  ✗ ROS2 repo not found at $ROS2_PATH (will be disabled)"
    cat >> "$REPOS_CONFIG" << EOF
  ros2:
    enabled: false
    path: null
    type: ros2
EOF
fi

# NLP repo
read -p "NLP service repo path [../nlp-service]: " NLP_PATH
NLP_PATH=${NLP_PATH:-../nlp-service}
NLP_ABS=$(cd "$PROJECT_ROOT" && cd "$NLP_PATH" 2>/dev/null && pwd || echo "")
if [ -n "$NLP_ABS" ] && [ -d "$NLP_ABS" ]; then
    echo "  ✓ NLP repo found: $NLP_ABS"
    cat >> "$REPOS_CONFIG" << EOF
  nlp:
    enabled: true
    path: $NLP_ABS
    type: nlp
EOF
else
    echo "  ✗ NLP repo not found at $NLP_PATH (will be disabled)"
    cat >> "$REPOS_CONFIG" << EOF
  nlp:
    enabled: false
    path: null
    type: nlp
EOF
fi

echo ""
echo "Configuration saved to $REPOS_CONFIG"
echo ""

# Generate .env file from .env.example
if [ ! -f "$PROJECT_ROOT/.env" ]; then
    if [ -f "$PROJECT_ROOT/.env.example" ]; then
        cp "$PROJECT_ROOT/.env.example" "$PROJECT_ROOT/.env"
        
        # Update .env with detected profile and paths
        sed -i.bak "s|^CROSSPLAY_PROFILE=.*|CROSSPLAY_PROFILE=$CROSSPLAY_PROFILE|" "$PROJECT_ROOT/.env"
        sed -i.bak "s|^VIDEO_PATH=.*|VIDEO_PATH=${VIDEO_ABS:-$VIDEO_PATH}|" "$PROJECT_ROOT/.env"
        sed -i.bak "s|^ROS2_PATH=.*|ROS2_PATH=${ROS2_ABS:-$ROS2_PATH}|" "$PROJECT_ROOT/.env"
        sed -i.bak "s|^NLP_PATH=.*|NLP_PATH=${NLP_ABS:-$NLP_PATH}|" "$PROJECT_ROOT/.env"
        rm -f "$PROJECT_ROOT/.env.bak"
        
        echo ".env file created from .env.example"
    else
        echo "WARNING: .env.example not found, creating basic .env"
        cat > "$PROJECT_ROOT/.env" << EOF
COMPOSE_PROJECT_NAME=crossplay
NETWORK_NAME=crossplay_net
CROSSPLAY_PROFILE=$CROSSPLAY_PROFILE
VIDEO_PATH=${VIDEO_ABS:-$VIDEO_PATH}
ROS2_PATH=${ROS2_ABS:-$ROS2_PATH}
NLP_PATH=${NLP_ABS:-$NLP_PATH}
VIDEO_PORT=8081
NLP_PORT=8082
ROS_DOMAIN_ID=0
EOF
    fi
else
    echo ".env file already exists, skipping creation"
fi

echo ""
echo "=== Setup Complete ==="
echo ""
echo "Next steps:"
echo "  1. Review and edit .env if needed"
echo "  2. Review config/crossplay.config.yaml"
echo "  3. Run ./scripts/launch.sh to start services"
echo ""

